require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor',        :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp',     :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
end

target 'App' do
  capacitor_pods
  # Add additional pods here if you ever need them
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
